
services:
  frontend:
    build: ./frontend
    ports:
     - "5001:5001"

  microusers:
    build: ./microUsers
    ports:
     - "5002:5002"
    depends_on:
     - db

  microproducts:
    build: ./microProducts
    ports:
     - "5003:5003"
    depends_on:
     - db

  microorders:
    build: ./microOrders
    ports:
     - "5004:5004"
    depends_on:
     - db

  db:
    image: mysql
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/